version: '3'
services:
  flaskapp:
    build: ./flask
    # volumes:
    #   - /Users/lizhiliang/Documents/Project/wishlist/wishlist/flask:/usr/app
    networks:
      - flask-net 
    depends_on:
      - db

  server:
    build: ./nginx
    ports:
      - 9977:8080
    networks:
      - flask-net
    depends_on:
      - flaskapp

  db:
    build: ./db
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - flask-net

networks:
  flask-net:
    driver: bridge

volumes:
  db-data: