version: "3"
services:
  web:
    image: bc9b068502cf
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  networks:
    webnet:
